### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by buaa-luzhi** [vsislab/VesselReID#1]
@Qianna00 能分享一下数据吗，仅用与算法效果验证，谢谢。

**Comment by Qianna00** [comment]
请发送邮件到info@vsislab.com获取下载链接

**Comment by Qianna00** [comment]
> @Qianna00 能分享一下数据吗，仅用与算法效果验证，谢谢。

请发送邮件到[info@vsislab.com](mailto:info@vsislab.com)获取下载链接
